### ISSUE TITLE
any chance to support more display like 2.7 or even more?

### ISSUE THREAD

**Issue by reddai75** [loiccoyle/tinyticker#45]
Hi,
can I ask you a little help to have more option to support more displays like the waveshare 2.7, or the 3.5 color display ?

**Comment by loiccoyle** [comment]
Sure! I don't have any of those displays but I'll gladly help.

**Comment by reddai75** [comment]
I can be your beta tester but unfortunately I have zero skills in programming:(

**Comment by loiccoyle** [comment]
Ok I'll see what I can do.

Do you know how to ssh into your rpi and install a dev branch of this project?

**Comment by reddai75** [comment]
Of course, if this tutorial is correct: https://www.squash.io/how-to-pip-install-from-a-git-repo-branch/ 😉

**Comment by loiccoyle** [comment]
I'm not sure about the 3.5 lcd display, I expect it will be a lot of work.

I'll start with the 2.7 epaper, do you mind telling me which one you have, there are 4 different 2.7inch epaper models:
- [B&W](https://www.waveshare.com/wiki/2.7inch_e-Paper_HAT_Manual#Introduction) (V1 and V2)
- [B&W&red](https://www.waveshare.com/wiki/2.7inch_e-Paper_HAT_(B)_Manual#Overview) (V1 and V2)

**Comment by loiccoyle** [comment]
ping @reddai75

**Comment by reddai75** [comment]
Sorry for the delay, I have to activate the notifications. 
I have the b&w V2.1 from waveshare, B&W

**Comment by loiccoyle** [comment]
hmm I agree it would be cool, but to implement something like that I would much prefer to buy a display to iterate quickly. So I'll keep it in mind, and maybe when/if I get a 2.7 display I'll look into it. 

Of course if someone with access to a 2.7in display want to take a stab at it I would gladly help.

> I have designed with my 3d printer an enclosure for the pi zero plus the 2.7 inches screen if you want.

Well seeing as I don't have a printer or  a 2.7in display it would be of no use to me, but I appreciate the  offer. :smile:

**Comment by loiccoyle** [comment]
Ok so I added `2in7_V2` epd model in the `feat/epd2in7_V2` branch. Keep in mind it is completely untested.

To install:
- ssh into the rpi
- `git clone https://github.com/loiccoyle/tinyticker`
- `cd tinyticker`
- `git switch feat/epd2in7_V2`
- `pip install --user --break-system-packages .`
- reboot the rpi
- set the display on the web interface and cross your fingers.

**Comment by loiccoyle** [comment]
> I have just had an idea, maybe is too much but since the 2.7 display has 4 buttons.... it would be incredibly useful if we could switch from one portfolio of stocks, to another, to crypto or to cycle 1hr candles to 1day/month by just pressing one button :)

Actually I recently made it so that `tinyticker` monitors the config flie (`~/.config/tinyticker/config.json`) and auto reloads when a change is detected (701074a0571ab718454ebce82c052dc104cda65d). So this could be implemented outside of `tinyticker` by writing a script to swap/change the config file when a button is pressed.

It should be relatively easy to implement and a good way to learn some basic programming/scripting.

**Comment by reddai75** [comment]
> Ok so I added `2in7_V2` epd model in the `feat/epd2in7_V2` branch. Keep in mind it is completely untested.
[...]

Hi! 
I installed it yesterday but from the scroll down menu I can't see any option regarding my screen...

**Comment by loiccoyle** [comment]
did you reboot the rpi? I just tried the web interface and the option is there:

![image](https://github.com/loiccoyle/tinyticker/assets/33181239/0b243bc0-e7a4-4cac-a922-51f499feff7b)

**Comment by reddai75** [comment]
So, I made the installation 4 times, with the display plugged and not plugged... The menu doesn't show the option 2.7... I have followed your instructions step by step..

**Comment by loiccoyle** [comment]
hmm very strange, I just went through it one more time and it works for me...

Whether or not the display is plugged in should not make a difference.

It will be hard to debug on github, I set up a `tinyticker` discord server where we can figure this out if you want.

https://discord.gg/ZXcxDq96

**Comment by reddai75** [comment]
Uh! I ssh-ing with the pi user, that must be the reason then .. easy fix!
I'll test it and come back to you asap, thank you!

**Comment by reddai75** [comment]
nothing, it does not work. Would you please send the invitation again to the discord channel ? 
thank you very much!

**Comment by loiccoyle** [comment]
https://discord.gg/4QmDswbU
