### ISSUE TITLE
Option to include pre-market and after hours data

### ISSUE THREAD

**Issue by MojoOne1** [loiccoyle/tinyticker#47]
Would it be possible to include an option to show pre-market and after hours data for stock tickers?

**Comment by loiccoyle** [comment]
I'm using `yfinance` to fetch the stock data, give me a bit to see if it possible. If it is I'll for sure implement it.

**Comment by loiccoyle** [comment]
see https://github.com/loiccoyle/tinyticker/pull/48

**Comment by loiccoyle** [comment]
Thanks for the suggestion btw.
