### ISSUE TITLE
Percentage Change Shown on TinyTicker Differs Slightly From Yahoo.com

### ISSUE THREAD

**Issue by mattrcarroll** [loiccoyle/tinyticker#65]
Hi,

Awesome project!  Thank you so much for sharing.  

For some reason, the end-of-day price change percentage (%) shown on my Tiny Ticker differs slightly from what is shown on Yahoo.com.  The price agrees exactly, but the percentage change is off.  I tried it on multiple tickers, and they are all off slightly.    For example, I have attached the screen captures for SPY and AGG and you will see the percentage changes on TinyTicker are slightly different than what is shown on Yahoo.com.  Are you able to fix, or maybe I am doing something wrong?  

Thank you for a great project. 
Matt

![AGG TinyTicker Display](https://github.com/user-attachments/assets/395dedc2-7b92-4f90-a8ef-5a04f0131bbc)
![SPY Tinyticker Display](https://github.com/user-attachments/assets/19c6c955-3ad7-46f3-be72-2b02e46ad5b9)
![AGG TinyTicker Configuration Screen](https://github.com/user-attachments/assets/1993136f-6b70-4652-bf9d-7f768ae9c155)
![AGG Yahoo com Screen Capture](https://github.com/user-attachments/assets/191bb1f6-b70a-4a1e-86d7-660baf3d0311)
![SPY TinyTicker Configuration Screen](https://github.com/user-attachments/assets/8750ffb2-73f0-4357-b50e-e3d4e011a87f)
![SPY Yahoo com Screen Shot](https://github.com/user-attachments/assets/676bb0e1-eeff-471f-99f1-47014e130775)

**Comment by loiccoyle** [comment]
I think it should be fixed on the main. I'm not able to test it currently, would you be able to test it before I create a new release? You would need to ssh into the pi with the tinyticker user, git clone and `pip install --user --break-system-packages .`. If you're not able to I'll just create a new release and cross my fingers, let me know.

**Comment by mattrcarroll** [comment]
Hi, Thank you for the quick response. Sorry, but I am away from home now and won’t be back for a few days. I could test later this week if you don’t release before then.  Thank you!Matt Sent from my iPhoneOn Nov 12, 2024, at 10:50 AM, Loïc Coyle ***@***.***> wrote:﻿
I think it should be fixed on the main. I'm not able to test it currently, would you be able to test it before I create a new release? You would need to ssh into the pi with the tinyticker user, git clone and pip install --user --break-system-packages .. If you're not able to I'll just create a new release and cross my fingers, let me know.

**Comment by loiccoyle** [comment]
No problem, I'll create a release then, it should be fine.

**Comment by loiccoyle** [comment]
When you get around to testing out the new release, please this issue if it is working.

**Comment by mattrcarroll** [comment]
Will do.  I should be able to do it tonight.

**Comment by mattrcarroll** [comment]
I just tested the new release and all looks good!  Thank you for such a
quick response and fix.  Best, Matt

**Comment by loiccoyle** [comment]
Glad to hear it.
